{{ include "common.serviceaccount" . }}
---
{{ include "common.configmap" . }}
---
{{ include "common.deployment" . }}
---
{{ include "common.service" . }}
---
{{ include "common.networkpolicy" . }}
---
{{ include "common.hpa" . }}
---
{{ include "common.pdb" . }}
---
{{ include "common.ingress" . }}
